//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by bigbang.rc
//
#define IDR_MANIFEST_LEGACY             1
#define IDR_IMP_TER_TOOLBAR             4
#define IDR_IMP_TER_TOOLBAR1            5
#define IDR_IMP_TER_DIS_TOOLBAR         5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MENUVIEW                    101
#define ID_INDICATOR_MESSAGE            101
#define IDD_PROPPAGE_SMALL              102
#define ID_INDICATOR_TRIANGLES          102
#define ID_INDICATOR_SNAPS              103
#define ID_INDICATOR_POSITION           104
#define ID_INDICATOR_FRAMERATE          105
#define IDR_MAINFRAME                   128
#define IDR_bigbang2TYPE                129
#define IDD_PAGE_TERRAIN                129
#define IDS_PAGE_ENTITY_CAPTION         129
#define IDR_TOOLBAR1                    130
#define IDS_PAGE_SHELL_CAPTION          130
#define IDD_PAGE_PROPERTIES             130
#define IDB_BITMAP1                     131
#define IDD_PAGE_OPTIONS                131
#define IDS_PAGE_MODEL_CAPTION          131
#define IDD_PAGE_PROJECT                132
#define IDS_PAGE_PREFAB_CAPTION         132
#define IDS_PAGE_PARTICLE_CAPTION       133
#define ID_MENU_DESELECTALL             134
#define ID_MENU_SELECTALL               135
#define ID_INDICATOR_CHUNKS             135
#define ID_MENU_SAVECAMERAPOSITION      136
#define IDS_PAGE_SPEEDTREE_CAPTION      137
#define IDS_NOLOADSKYBOX                138
#define IDS_NOLOADSKYDOME               139
#define ID_MENU_SAVETEMPLATE            140
#define IDS_NOTRESPATH                  141
#define IDS_FAILED_IMPORT_TERRAIN       142
#define IDS_EBM_ADDITIVE                143
#define IDS_EBM_SUBTRACTIVE             144
#define IDS_EBM_OVERLAY                 145
#define IDS_EBM_MIN                     146
#define IDS_EBM_MAX                     147
#define IDS_EBM_REPLACE                 148
#define IDS_LARGE_IMPORT                149
#define ID_MENU_SAVESTARTPOSITION       150
#define IDS_PAGE_LIGHT_CAPTION          151
#define IDS_PAGE_MISC_CAPTION           152
#define ID_MENU_SHOWSIDEPANEL           153
#define IDS_SHEET_MENU                  154
#define IDS_BADCODEC_IMPORT_TERRAIN     155
#define IDD_PAGE_OBJECT_MODEL_BROWSE    156
#define IDS_FILESMUSTDIFFER             156
#define IDS_NOLOADSKYGRADIENT           157
#define IDD_PAGE_TERRAIN_TEXTURE        158
#define ID_INDICATOR_MEMORYLOAD         158
#define IDD_PAGE_TERRAIN_HEIGHT         159
#define IDD_PAGE_TERRAIN_FILTER         160
#define IDD_PAGE_TERRAIN_MESH           161
#define IDD_PAGE_ERRORS                 162
#define ID_MENU_SAVEPREFAB              163
#define IDD_PAGE_SCENE                  163
#define IDD_DIALOG_ACTIONS              164
#define IDR_SCENE_ICONS                 166
#define IDR_SCENE_POPUP                 166
#define ID_SCENE_POPUP_INSERT           167
#define ID_SCENE_POPUP_DELETE           168
#define ID_POPUP_RENAME                 169
#define ID_SCENE_POPUP_RENAME           170
#define ID_Menu                         171
#define ID_SCENE_POPUP_MOVESELECTIONHERE 172
#define IDR_PROPERTIES_LIST_POPUP       174
#define IDR_PROPERTIES_LISTITEM_POPUP   175
#define ID_PROPERTIES_LIST_POPUP_ADDITEM 176
#define ID_PROPERTIES_LISTITEM_POPUP_REMOVEITEM 177
#define ID_HELP_HELP                    178
#define IDD_MODELESS_INFO               179
#define ID_FILE_IMPORT                  180
#define IDD_PAGE_OBJECT1                180
#define IDD_PAGE_OPTIONSHEET            180
#define ID_FILE_EXPORT                  181
#define IDD_PAGE_OPTIONS_GENERAL        181
#define IDD_PAGE_OPTIONS_GENERAL1       182
#define IDD_PAGE_OPTIONS_WEATHER        182
#define IDB_BITMAP2                     182
#define IDB_ABOUTBOX                    182
#define IDD_PAGE_OPTIONS_HISTOGRAM      183
#define IDB_BITMAP3                     183
#define IDB_SPLASH                      183
#define IDD_DIALOG1                     184
#define IDD_SPLASH                      184
#define IDD_HTMLDIALOG                  189
#define IDR_HTML1                       191
#define IDR_KEY_CUTS                    194
#define ID_HELP_KEY_CUTS                211
#define IDD_DIALOG2                     212
#define IDD_NEWSPACE                    212
#define IDD_PLACEMENT_CTRLS             213
#define IDD_RANDNEWPRESET               214
#define IDI_ICON1                       215
#define IDI_PLACEMENT_RESET             215
#define IDI_PLACEMENT_LINK              216
#define IDI_PLACEMENT_LINKUP            217
#define IDI_ICON2                       218
#define IDI_PLACEMENT_LINKDOWN          218
#define IDD_PAGE_OPTIONS_ENVIRONMENT    219
#define IDC_HEIGHTPICKER                220
#define IDD_LIMITSLIDER                 221
#define IDD_PAGE_OBJECTS                222
#define IDD_PAGE_TERRAIN_IMPORT         223
#define IDD_RAW_IMPORT_DLG              229
#define IDR_SKYDOME_TB                  230
#define IDR_SKYDOME_DIS_TB              231
#define IDB_OPEN                        232
#define IDB_OPEND                       233
#define IDB_NEWFILE                     234
#define IDB_NEWFILED                    235
#define IDB_DUPLICATE                   236
#define IDB_DUPLICATED                  237
#define IDD_WAITDLG                     237
#define IDD_ERRORS                      238
#define IDB_RANGESLIDER                 241
#define IDD_OUT_OF_MEMORY               242
#define IDC_SELECTION_FILTER            900
#define IDC_COORDINATION_FILTER         901
#define IDC_PROPSHEET_PLACEHOLDER       1001
#define IDC_PROPSHEET_OBJECT_PLACEHOLDER 1002
#define IDC_OBJECT_ENTITY_DIR_LIST      1004
#define IDC_TERRAIN_FALLOFF_CURVE3      1005
#define IDC_TERRAIN_RELATIVEHEIGHT      1006
#define IDC_OBJECT_ENTITY_FILE_LIST     1007
#define IDC_OBJECT_ENTITY_CURRENT_DIR   1008
#define IDC_OBJECT_MODEL_CURRENT_DIR    1009
#define IDC_OBJECT_SHELL_CURRENT_DIR    1011
#define IDC_OBJECT_CURRENT_DIR          1013
#define IDC_OBJECT_DIR_LIST             1014
#define IDC_OBJECT_FILE_LIST            1015
#define IDC_LIST2                       1022
#define IDC_OBJECT_PLACE_NORMAL         1023
#define IDC_OBJECT_PLACE_ROTATED        1024
#define IDC_OBJECT_PLACE_ROTATED_SCALED 1025
#define IDC_PROPSHEET_TERRAIN_PLACEHOLDER 1026
#define IDC_TERRAIN_ALPHA_CHANNEL1      1031
#define IDC_TERRAIN_ALPHA_CHANNEL2      1032
#define IDC_TERRAIN_ALPHA_CHANNEL3      1033
#define IDC_TERRAIN_ALPHA_CHANNEL4      1034
#define IDC_TERRAIN_CURRENT_DIR         1035
#define IDC_TERRAIN_DIR_LIST            1036
#define IDC_TERRAIN_SIZE_SLIDER         1037
#define IDC_TERRAIN_SIZE_EDIT           1038
#define IDC_TERRAIN_STRENGTH_SLIDER     1039
#define IDC_TERRAIN_STRENGTH_EDIT       1040
#define IDC_TERRAIN_HEIGHT_SLIDER       1041
#define IDC_TERRAIN_HEIGHT_EDIT         1042
#define IDC_TERRAIN_FALLOFF_LINEAR      1043
#define IDC_TERRAIN_FALLOFF_CURVE       1044
#define IDC_TERRAIN_ABSOLUTEHEIGHT      1045
#define IDC_TERRAIN_WIREFRAME           1046
#define IDC_TERRAIN_FALLOFF_FLAT        1047
#define IDC_TERRAIN_FILTERS_LIST        1048
#define IDC_TERRAIN_CUT                 1049
#define IDC_TERRAIN_REPAIR              1050
#define IDC_OPTIONS_SHELL_SHOWALL       1051
#define IDC_OPTIONS_SHELL_GAMEVISIBILITY 1052
#define IDC_OPTIONS_SCENERY_SHOW        1053
#define IDC_OPTIONS_SCENERY_WIREFRAME   1055
#define IDC_OPTIONS_TERRAIN_SHOW        1057
#define IDC_OPTIONS_TERRAIN_WIREFRAME   1060
#define IDC_OPTIONS_LIGHTING_STANDARD   1061
#define IDC_OPTIONS_LIGHTING_DYNAMIC    1062
#define IDC_OPTIONS_LIGHTING_SPECULAR   1063
#define IDC_OPTIONS_SHOW_TREE           1064
#define IDC_OPTIONS_BSP_NORMAL          1065
#define IDC_OPTIONS_BSP_CUSTOM          1066
#define IDC_OPTIONS_FARPLANE_SLIDER     1067
#define IDC_OPTIONS_FARPLANE_EDIT       1068
#define IDC_OPTIONS_SNAPS_X             1069
#define IDC_OPTIONS_SNAPS_Y             1070
#define IDC_OPTIONS_SNAPS_Z             1071
#define IDC_OPTIONS_SNAPS_ANGLE         1072
#define IDC_OPTIONS_SHELLSNAPS          1073
#define IDC_OPTIONS_UNITSNAPS           1074
#define IDC_OPTIONS_POINTONESNAPS       1075
#define IDC_OPTIONS_BSP_ALL             1076
#define IDC_OPTIONS_CAMERAHEIGHT_SLIDER 1077
#define IDC_OPTIONS_CAMERAHEIGHT_EDIT   1078
#define IDC_SCENE_COLOUR_RED            1079
#define IDC_SCENE_COLOUR_GREEN          1080
#define IDC_SCENE_COLOUR_BLUE           1081
#define IDC_SCENE_COLOURBOX             1082
#define IDC_SCENE_COLOUR_BLUE_STATIC    1083
#define IDC_SCENE_COLOUR_GREEN_STATIC   1084
#define IDC_SCENE_COLOUR_RED_STATIC     1085
#define IDC_SCENE_LIGHT_MULTIPLIER      1086
#define IDC_PROJECT_CONNECT             1087
#define IDC_PROJECT_COMMIT_MESSAGE      1088
#define IDC_PROJECT_COMMIT_KEEPLOCKS    1089
#define IDC_PROJECT_COMMIT_ALL          1090
#define IDC_PROJECT_DISCARD_KEEPLOCKS   1091
#define IDC_PROJECT_DISCARD_ALL         1092
#define IDC_PROJECT_SETTINGS            1093
#define IDC_ERROR_LIST                  1094
#define IDC_ERRORS_LIST                 1095
#define IDC_OPTIONS_TIMEOFDAY_EDIT      1096
#define IDC_OPTIONS_TIMEOFDAY_SLIDER    1097
#define IDC_OPTIONS_REMEMBER_SELECTION_FILTER 1098
#define IDC_SCENE_TREE                  1099
#define IDC_DIALOG_ACTION_CURRENT       1100
#define IDC_OPTIONS_READ_ONLY_MODE      1101
#define IDC_DIALOG_ACTION_DELETE        1102
#define IDC_DIALOG_ACTION_EVENT         1103
#define IDC_DIALOG_ACTION_ACTION        1104
#define IDC_DIALOG_ACTION_ADD           1105
#define IDC_DIALOG_ACTION_CHANGE        1106
#define IDC_SKYDOME_LIST                1108
#define IDC_PROJECT_MAP_ALPHA_SLIDER    1112
#define IDC_INFO                        1113
#define IDC_BUTTON1                     1114
#define IDC_TODFILE_BTN                 1114
#define IDC_WEATHER_RESETALL            1115
#define IDC_NEWTODFILE_BTN              1115
#define IDC_HIST_UPDATE                 1116
#define IDC_RANDROTX_RESET              1117
#define IDC_ADDCOLOR_BTN                1118
#define IDC_SIZERANGE                   1119
#define IDC_NEWSPACE_BROWSE             1120
#define IDC_WEATHERSETTINGSSTATIC       1121
#define IDC_RANDROTY_RESET              1122
#define IDC_STRENGTHRANGE               1123
#define IDC_PROPSHEET_OPTION_PLACEHOLDER 1124
#define IDC_RANDROTZ_RESET              1125
#define IDC_HEIGHTRANGE                 1126
#define IDC_BUTTON2                     1127
#define IDC_SETTINGSFILE_BTN            1127
#define IDC_DUMMYHIT                    1128
#define IDC_RANDSCAX_RESET              1129
#define IDC_DELCOLOR_BTN                1130
#define IDC_PROJECT_CANCEL_BTN          1131
#define IDC_EDIT_PLACEMENT_SETTINGS     1132
#define IDC_OBJECTS_EDIT_PLACEMENT_SETTINGS 1133
#define IDC_WEATHER_SETDEFAULTS         1134
#define IDC_RANDSCAY_RESET              1135
#define IDC_STATIC_RANGE                1136
#define IDC_MESH_ACTION                 1137
#define IDC_SPACE                       1138
#define IDC_WIDTH                       1139
#define IDC_HEIGHT                      1140
#define IDC_PROGRESS1                   1141
#define IDC_SPACE_PATH                  1142
#define IDC_LIMITCONTROL                1143
#define IDC_MINEDIT                     1144
#define IDC_MAXEDIT                     1145
#define IDC_SUNANGLE_EDIT               1146
#define IDC_MOONANGLE_EDIT              1147
#define IDC_RANDROTY_MIN                1148
#define IDC_RANDPRESETS                 1149
#define IDC_RANDROTY_MAX                1150
#define IDC_RANDROTZ_MIN                1151
#define IDC_RANDROTZ_MAX                1152
#define IDC_RANDSCAY_MIN                1153
#define IDC_RANDSCAY_MAX                1154
#define IDC_RANDSCAZ_MIN                1155
#define IDC_RANDSCAZ_MAX                1156
#define IDC_RANDSCA_LINK                1157
#define IDC_RANDROT_LINK                1158
#define IDC_RANDPRESETSLABEL            1159
#define IDC_RANDROT_GRP                 1160
#define IDC_RANDSCA_GRP                 1161
#define IDC_RANDROT_LINKUP              1162
#define IDC_RANDROT_LINKDOWN            1163
#define IDC_RANDSCA_LINKUP              1164
#define IDC_RANDSCA_LINKDOWN            1165
#define IDC_SEP2                        1167
#define IDC_SEP1                        1168
#define IDC_COLORTIMELINE               1169
#define IDC_COLORPICKER                 1170
#define IDC_SEP3                        1171
#define IDC_SEP4                        1172
#define IDC_TIMEOFDAY_EDIT              1173
#define IDC_TIMEOFDAY_SLIDER            1174
#define IDC_SUNANIM_BTN                 1175
#define IDC_AMBANIM_BTN                 1176
#define IDC_CREATEANIM_BTN              1178
#define IDC_REMOVEANIM_BTN              1179
#define IDC_R_EDIT                      1180
#define IDC_G_EDIT                      1181
#define IDC_B_EDIT                      1182
#define IDC_MIEAMOUNT                   1183
#define IDC_TURBOFFS                    1184
#define IDC_VERTHEIGHTEFFECT            1185
#define IDC_TURBFACTOR                  1186
#define IDC_SUNHEIGHTEFFECT             1187
#define IDC_POWER                       1188
#define IDC_SEP5                        1189
#define IDC_SB_GRAD_EDIT                1190
#define IDC_SB_GRAD_BTN                 1191
#define IDC_SEP6                        1192
#define IDC_ADDSKYDOME_BTN              1194
#define IDC_CLEARSKYDOME_BTN            1195
#define IDC_RANGER                      1196
#define IDC_MIEAMOUNT_SLIDER            1197
#define IDC_PROJECT_VERSIONCONTROL_GROUP 1198
#define IDC_TURBFACTOR_SLIDER           1199
#define IDC_TERIMP_IMPORT_GROUP         1200
#define IDC_BUTTON3                     1201
#define IDC_BUTTON4                     1202
#define IDC_POWER_SLIDER                1203
#define IDC_MINLIMIT                    1204
#define IDC_MAXLIMIT                    1205
#define IDC_CALCULATEDMAP               1206
#define IDC_OBJECTS_SELECTION_FILTER    1207
#define IDC_OBJECTS_SELECT_PLACEMENT_SETTING 1208
#define IDC_OBJECTS_LIGHTING_STANDARD   1209
#define IDC_OBJECTS_LIGHTING_SPECULAR   1210
#define IDC_OBJECTS_LIGHTING_DYNAMIC    1211
#define IDC_OBJECTS_COORDS_WORLD        1212
#define IDC_OBJECTS_COORDS_LOCAL        1213
#define IDC_OBJECTS_COORDS_VIEW         1214
#define IDC_OBJECTS_LOCK_FREE           1215
#define IDC_OBJECTS_LOCK_TERRAIN        1216
#define IDC_OBJECTS_LOCK_OBSTACLE       1217
#define IDC_TERIMP_IMPORT_FILE          1218
#define IDC_TERIMP_PLACE_BTN            1219
#define IDC_TERIMP_BROWSE_BTN           1222
#define IDC_TERIMP_EXPORT_BTN           1223
#define IDC_TERIMP_FILE_STATIC          1225
#define IDC_TERIMP_MODE_CB              1227
#define IDC_TERIMP_MAP_ALPHA_SLIDER     1228
#define IDC_TERIMP_ACTIONTB             1229
#define IDC_TERIMP_ANTICLOCKWISE_BTN    1230
#define IDC_TERIMP_CLOCKWISE_BTN        1231
#define IDC_TERIMP_FLIPX_BTN            1232
#define IDC_TERIMP_FLIPY_BTN            1233
#define IDC_TERIMP_FLIPH_BTN            1234
#define IDC_TERIMP_RECALCCLR_BTN        1235
#define IDC_TERIMP_MIN_EDIT             1236
#define IDC_TERIMP_MIN_SLIDER           1237
#define IDC_TERIMP_MAX_EDIT             1238
#define IDC_TERIMP_MAX_SLIDER           1239
#define IDC_TERIMP_STRENGTH_EDIT        1240
#define IDC_TERIMP_STRENGTH_SLIDER      1241
#define IDC_TERIMP_CANCEL_BTN           1242
#define IDC_TERIMP_HANDDRAWN_GROUP      1243
#define IDC_TERIMP_HEIGHT_SLIDER        1244
#define IDC_TEXTURECHANNEL1             1245
#define IDC_TEXTURECHANNEL2             1246
#define IDC_TEXTURECHANNEL3             1247
#define IDC_TEXTURECHANNEL4             1248
#define IDC_RAWIMP_LITTLEENDIAN         1250
#define IDC_RAWIMP_BIGENDIAN            1251
#define IDC_RAWIMP_FILENAME             1252
#define IDC_RAWIMP_BMP                  1253
#define IDC_RAWIMP_SIZE                 1254
#define IDC_NEWSPACE_WIDTH_KM           1255
#define IDC_NEWSPACE_HEIGHT_KM          1256
#define IDC_SKYDOME_TB                  1257
#define IDC_LUMINANCE                   1258
#define IDC_RANDSCAZ_RESET              1259
#define IDC_RGB                         1260
#define IDC_BUILDTIME                   1261
#define IDC_RED                         1262
#define IDC_GREEN                       1263
#define IDC_BLUE                        1264
#define IDC_SLIDER1                     1265
#define IDC_RANGERATIOSLIDER            1266
#define IDC_RANDROTX_RANGE              1267
#define IDC_SUNANGLE_SLIDER             1268
#define IDC_SLIDER                      1269
#define IDC_PROJECT_MIN_SLIDER          1270
#define IDC_RANGERATIO                  1271
#define IDC_RANDROTY_RANGE              1272
#define IDC_MOONANGLE_SLIDER            1273
#define IDC_CHECK1                      1274
#define IDC_HIST_AUTOUPDATE             1275
#define IDC_CHANGESPACE                 1276
#define IDC_RANDROTX_CHK                1277
#define IDC_RANDSCA_UNI                 1278
#define IDC_OBJECTS_DRAG_ON_SELECT      1279
#define IDC_PLAYER_PREVIEW_MODE         1280
#define IDC_RANDSCAX_RANGE              1281
#define IDC_CHECK2                      1282
#define IDC_OBJECTS_LOCK_TO_GRID        1283
#define IDC_RANDSCAY_RANGE              1284
#define IDC_RANDSCA_CHK                 1285
#define IDC_STATIC_LUM                  1286
#define IDC_RANDROTZ_RANGE              1287
#define IDC_STATIC_RGB                  1288
#define IDC_RANDSCAX_RANGE3             1289
#define IDC_RANDSCAZ_RANGE              1290
#define IDC_TERRAIN_FILE_LIST           1291
#define IDC_SCENE_PROPERTYLIST          1292
#define IDC_OPTIONS_BSP_DYNAMIC         1293
#define IDC_OPTIONS_FARPLANE_SLIDER2    1294
#define IDC_PROJECT_SELECTION_LOCK      1295
#define IDC_SCENE_COLOUR_BLUE_STATIC2   1296
#define IDC_SCENE_LIGHT_MULTIPLIER_STATIC 1297
#define IDC_OPTIONS_REMEMBER_SELECTION_FILTER2 1298
#define IDC_LIST1                       1299
#define IDC_HOTKEY1                     1300
#define IDC_SPACE2                      1301
#define IDC_TODFILE_EDIT                1302
#define IDC_EDITSLAVE                   1303
#define IDC_RANDROTX_MIN                1304
#define IDC_NEWPLACEMENTTEXT            1305
#define IDC_HOURLENGTH                  1306
#define IDC_RANDROTX_MAX                1307
#define IDC_STARTTIME                   1308
#define IDC_RANDSCAX_MIN                1309
#define IDC_RANDSCAX_MAX                1310
#define IDC_SUN_COLORS                  1311
#define IDC_SUN_COLORS_PICKER           1312
#define IDC_TURBOFFS_SLIDER             1313
#define IDC_VERTHEIGHTEFFECT_SLIDER     1314
#define IDC_SUNHEIGHTEFFECT_SLIDER      1315
#define IDC_SLIDER7                     1316
#define IDC_OBJECTS_COORD_FILTER        1317
#define IDC_OBJECTS_SELECTION_FILTER2   1318
#define IDC_SKYFILE_EDIT                1319
#define IDC_SKYFILE_BTN                 1320
#define IDC_SETTINGSFILE_EDIT           1321
#define IDC_NEWSKYFILE_BTN              1322
#define IDC_TEXTURESINCHUNK             1323
#define IDC_WAITDLG_INFO                1324
#define IDC_PROJECT_UPDATE              1325
#define IDC_SAVE                        1326
#define IDC_CONTINUE                    1327
#define IDC_MSG_LIST                    1700
#define IDC_MSG_SHOW_DATE               1701
#define IDC_MSG_SHOW_TIME               1702
#define IDC_MSG_SHOW_PRIORITY           1703
#define IDC_MSG_ERROR                   1704
#define IDC_MSG_WARNING                 1705
#define IDC_MSG_NOTICE                  1706
#define IDC_MSG_INFO                    1707
#define IDC_MSG_ASSETS                  1708
#define ID_BUTTON_MOVESPEED1            32771
#define ID_BUTTON_MOVESPEED2            32772
#define ID_BUTTON_MOVESPEED3            32773
#define ID_BUTTON_MOVESPEED4            32774
#define ID_BUTTON_BG_UPDATE             32784
#define ID_BUTTON_QUICKSAVE             32785
#define ID_BUTTON_FULLSAVE              32786
#define ID_BUTTON_LOAD_ALL              32787
#define ID_BUTTON_COORD_WORLD           32795
#define ID_BUTTON_COORD_OBJECT          32796
#define ID_BUTTON_COORD_VIEW            32797
#define ID_BUTTON_PLAYER_PREVIEW        32798
#define ID_TOOL_OBJECT                  32805
#define ID_TOOL_TERRAIN_TEXTURE         32806
#define ID_TOOL_TERRAIN_HEIGHT          32807
#define ID_TOOL_TERRAIN_FILTER          32808
#define ID_TOOL_TERRAIN_MESH            32809
#define ID_TOOL_PROJECT                 32810
#define IDC_SKYDOME_UP                  32821
#define IDC_SKYDOME_DOWN                32822
#define IDC_SKYDOME_DEL                 32823
#define ID_BUTTON_UNDO                  32998
#define ID_BUTTON_REDO                  32999
#define ID_SELECTION_FILTER_PLACEHOLDER 33000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1327
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
