/* soapH.h
   Generated by gSOAP 2.7.13 from Register.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_ns1__AutoActResultCode
#define SOAP_TYPE_ns1__AutoActResultCode (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__AutoActResultCode(struct soap*, enum ns1__AutoActResultCode *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__AutoActResultCode(struct soap*, const enum ns1__AutoActResultCode *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__AutoActResultCode(struct soap*, const char*, int, const enum ns1__AutoActResultCode *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns1__AutoActResultCode2s(struct soap*, enum ns1__AutoActResultCode);
SOAP_FMAC3 enum ns1__AutoActResultCode * SOAP_FMAC4 soap_get_ns1__AutoActResultCode(struct soap*, enum ns1__AutoActResultCode *, const char*, const char*);
SOAP_FMAC3 enum ns1__AutoActResultCode * SOAP_FMAC4 soap_in_ns1__AutoActResultCode(struct soap*, const char*, enum ns1__AutoActResultCode *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns1__AutoActResultCode(struct soap*, const char*, enum ns1__AutoActResultCode *);

#ifndef SOAP_TYPE_ns3__AdultStatusResult
#define SOAP_TYPE_ns3__AdultStatusResult (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__AdultStatusResult(struct soap*, const char*, int, const ns3__AdultStatusResult *, const char*);
SOAP_FMAC3 ns3__AdultStatusResult * SOAP_FMAC4 soap_get_ns3__AdultStatusResult(struct soap*, ns3__AdultStatusResult *, const char*, const char*);
SOAP_FMAC3 ns3__AdultStatusResult * SOAP_FMAC4 soap_in_ns3__AdultStatusResult(struct soap*, const char*, ns3__AdultStatusResult *, const char*);

#define soap_new_ns3__AdultStatusResult(soap, n) soap_instantiate_ns3__AdultStatusResult(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__AdultStatusResult(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__AdultStatusResult * SOAP_FMAC4 soap_instantiate_ns3__AdultStatusResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__AdultStatusResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__BlockRecord
#define SOAP_TYPE_ns3__BlockRecord (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__BlockRecord(struct soap*, const char*, int, const ns3__BlockRecord *, const char*);
SOAP_FMAC3 ns3__BlockRecord * SOAP_FMAC4 soap_get_ns3__BlockRecord(struct soap*, ns3__BlockRecord *, const char*, const char*);
SOAP_FMAC3 ns3__BlockRecord * SOAP_FMAC4 soap_in_ns3__BlockRecord(struct soap*, const char*, ns3__BlockRecord *, const char*);

#define soap_new_ns3__BlockRecord(soap, n) soap_instantiate_ns3__BlockRecord(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__BlockRecord(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__BlockRecord * SOAP_FMAC4 soap_instantiate_ns3__BlockRecord(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__BlockRecord(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__QueryAccountBlockHistoryResult
#define SOAP_TYPE_ns3__QueryAccountBlockHistoryResult (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__QueryAccountBlockHistoryResult(struct soap*, const char*, int, const ns3__QueryAccountBlockHistoryResult *, const char*);
SOAP_FMAC3 ns3__QueryAccountBlockHistoryResult * SOAP_FMAC4 soap_get_ns3__QueryAccountBlockHistoryResult(struct soap*, ns3__QueryAccountBlockHistoryResult *, const char*, const char*);
SOAP_FMAC3 ns3__QueryAccountBlockHistoryResult * SOAP_FMAC4 soap_in_ns3__QueryAccountBlockHistoryResult(struct soap*, const char*, ns3__QueryAccountBlockHistoryResult *, const char*);

#define soap_new_ns3__QueryAccountBlockHistoryResult(soap, n) soap_instantiate_ns3__QueryAccountBlockHistoryResult(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__QueryAccountBlockHistoryResult(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__QueryAccountBlockHistoryResult * SOAP_FMAC4 soap_instantiate_ns3__QueryAccountBlockHistoryResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__QueryAccountBlockHistoryResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__QueryStringResult
#define SOAP_TYPE_ns3__QueryStringResult (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__QueryStringResult(struct soap*, const char*, int, const ns3__QueryStringResult *, const char*);
SOAP_FMAC3 ns3__QueryStringResult * SOAP_FMAC4 soap_get_ns3__QueryStringResult(struct soap*, ns3__QueryStringResult *, const char*, const char*);
SOAP_FMAC3 ns3__QueryStringResult * SOAP_FMAC4 soap_in_ns3__QueryStringResult(struct soap*, const char*, ns3__QueryStringResult *, const char*);

#define soap_new_ns3__QueryStringResult(soap, n) soap_instantiate_ns3__QueryStringResult(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__QueryStringResult(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__QueryStringResult * SOAP_FMAC4 soap_instantiate_ns3__QueryStringResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__QueryStringResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__ProcessResult
#define SOAP_TYPE_ns3__ProcessResult (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__ProcessResult(struct soap*, const char*, int, const ns3__ProcessResult *, const char*);
SOAP_FMAC3 ns3__ProcessResult * SOAP_FMAC4 soap_get_ns3__ProcessResult(struct soap*, ns3__ProcessResult *, const char*, const char*);
SOAP_FMAC3 ns3__ProcessResult * SOAP_FMAC4 soap_in_ns3__ProcessResult(struct soap*, const char*, ns3__ProcessResult *, const char*);

#define soap_new_ns3__ProcessResult(soap, n) soap_instantiate_ns3__ProcessResult(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__ProcessResult(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__ProcessResult * SOAP_FMAC4 soap_instantiate_ns3__ProcessResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__ProcessResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__Exception
#define SOAP_TYPE_ns2__Exception (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Exception(struct soap*, const char*, int, const ns2__Exception *, const char*);
SOAP_FMAC3 ns2__Exception * SOAP_FMAC4 soap_get_ns2__Exception(struct soap*, ns2__Exception *, const char*, const char*);
SOAP_FMAC3 ns2__Exception * SOAP_FMAC4 soap_in_ns2__Exception(struct soap*, const char*, ns2__Exception *, const char*);

#define soap_new_ns2__Exception(soap, n) soap_instantiate_ns2__Exception(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__Exception(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns2__Exception * SOAP_FMAC4 soap_instantiate_ns2__Exception(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__Exception(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__RegisterResponse
#define SOAP_TYPE__ns1__RegisterResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__RegisterResponse(struct soap*, const char*, int, const _ns1__RegisterResponse *, const char*);
SOAP_FMAC3 _ns1__RegisterResponse * SOAP_FMAC4 soap_get__ns1__RegisterResponse(struct soap*, _ns1__RegisterResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__RegisterResponse * SOAP_FMAC4 soap_in__ns1__RegisterResponse(struct soap*, const char*, _ns1__RegisterResponse *, const char*);

#define soap_new__ns1__RegisterResponse(soap, n) soap_instantiate__ns1__RegisterResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__RegisterResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__RegisterResponse * SOAP_FMAC4 soap_instantiate__ns1__RegisterResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__RegisterResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Register
#define SOAP_TYPE__ns1__Register (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Register(struct soap*, const char*, int, const _ns1__Register *, const char*);
SOAP_FMAC3 _ns1__Register * SOAP_FMAC4 soap_get__ns1__Register(struct soap*, _ns1__Register *, const char*, const char*);
SOAP_FMAC3 _ns1__Register * SOAP_FMAC4 soap_in__ns1__Register(struct soap*, const char*, _ns1__Register *, const char*);

#define soap_new__ns1__Register(soap, n) soap_instantiate__ns1__Register(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__Register(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__Register * SOAP_FMAC4 soap_instantiate__ns1__Register(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Register(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__GameAutoActivateResult
#define SOAP_TYPE_ns1__GameAutoActivateResult (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__GameAutoActivateResult(struct soap*, const char*, int, const ns1__GameAutoActivateResult *, const char*);
SOAP_FMAC3 ns1__GameAutoActivateResult * SOAP_FMAC4 soap_get_ns1__GameAutoActivateResult(struct soap*, ns1__GameAutoActivateResult *, const char*, const char*);
SOAP_FMAC3 ns1__GameAutoActivateResult * SOAP_FMAC4 soap_in_ns1__GameAutoActivateResult(struct soap*, const char*, ns1__GameAutoActivateResult *, const char*);

#define soap_new_ns1__GameAutoActivateResult(soap, n) soap_instantiate_ns1__GameAutoActivateResult(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__GameAutoActivateResult(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns1__GameAutoActivateResult * SOAP_FMAC4 soap_instantiate_ns1__GameAutoActivateResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__GameAutoActivateResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns5__Register
#define SOAP_TYPE___ns5__Register (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns5__Register(struct soap*, struct __ns5__Register *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns5__Register(struct soap*, const struct __ns5__Register *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns5__Register(struct soap*, const struct __ns5__Register *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns5__Register(struct soap*, const char*, int, const struct __ns5__Register *, const char*);
SOAP_FMAC3 struct __ns5__Register * SOAP_FMAC4 soap_get___ns5__Register(struct soap*, struct __ns5__Register *, const char*, const char*);
SOAP_FMAC3 struct __ns5__Register * SOAP_FMAC4 soap_in___ns5__Register(struct soap*, const char*, struct __ns5__Register *, const char*);

#define soap_new___ns5__Register(soap, n) soap_instantiate___ns5__Register(soap, n, NULL, NULL, NULL)


#define soap_delete___ns5__Register(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns5__Register * SOAP_FMAC4 soap_instantiate___ns5__Register(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns5__Register(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__Register
#define SOAP_TYPE___ns4__Register (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__Register(struct soap*, struct __ns4__Register *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__Register(struct soap*, const struct __ns4__Register *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__Register(struct soap*, const struct __ns4__Register *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__Register(struct soap*, const char*, int, const struct __ns4__Register *, const char*);
SOAP_FMAC3 struct __ns4__Register * SOAP_FMAC4 soap_get___ns4__Register(struct soap*, struct __ns4__Register *, const char*, const char*);
SOAP_FMAC3 struct __ns4__Register * SOAP_FMAC4 soap_in___ns4__Register(struct soap*, const char*, struct __ns4__Register *, const char*);

#define soap_new___ns4__Register(soap, n) soap_instantiate___ns4__Register(soap, n, NULL, NULL, NULL)


#define soap_delete___ns4__Register(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns4__Register * SOAP_FMAC4 soap_instantiate___ns4__Register(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__Register(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__UpdatePassword
#define SOAP_TYPE_ns2__UpdatePassword (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__UpdatePassword(struct soap*, struct ns2__UpdatePassword *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__UpdatePassword(struct soap*, const struct ns2__UpdatePassword *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__UpdatePassword(struct soap*, const struct ns2__UpdatePassword *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__UpdatePassword(struct soap*, const char*, int, const struct ns2__UpdatePassword *, const char*);
SOAP_FMAC3 struct ns2__UpdatePassword * SOAP_FMAC4 soap_get_ns2__UpdatePassword(struct soap*, struct ns2__UpdatePassword *, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdatePassword * SOAP_FMAC4 soap_in_ns2__UpdatePassword(struct soap*, const char*, struct ns2__UpdatePassword *, const char*);

#define soap_new_ns2__UpdatePassword(soap, n) soap_instantiate_ns2__UpdatePassword(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__UpdatePassword(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__UpdatePassword * SOAP_FMAC4 soap_instantiate_ns2__UpdatePassword(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__UpdatePassword(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__UpdatePasswordResponse
#define SOAP_TYPE_ns2__UpdatePasswordResponse (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__UpdatePasswordResponse(struct soap*, struct ns2__UpdatePasswordResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__UpdatePasswordResponse(struct soap*, const struct ns2__UpdatePasswordResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__UpdatePasswordResponse(struct soap*, const struct ns2__UpdatePasswordResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__UpdatePasswordResponse(struct soap*, const char*, int, const struct ns2__UpdatePasswordResponse *, const char*);
SOAP_FMAC3 struct ns2__UpdatePasswordResponse * SOAP_FMAC4 soap_get_ns2__UpdatePasswordResponse(struct soap*, struct ns2__UpdatePasswordResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdatePasswordResponse * SOAP_FMAC4 soap_in_ns2__UpdatePasswordResponse(struct soap*, const char*, struct ns2__UpdatePasswordResponse *, const char*);

#define soap_new_ns2__UpdatePasswordResponse(soap, n) soap_instantiate_ns2__UpdatePasswordResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__UpdatePasswordResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__UpdatePasswordResponse * SOAP_FMAC4 soap_instantiate_ns2__UpdatePasswordResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__UpdatePasswordResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__Suspend
#define SOAP_TYPE_ns2__Suspend (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__Suspend(struct soap*, struct ns2__Suspend *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__Suspend(struct soap*, const struct ns2__Suspend *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__Suspend(struct soap*, const struct ns2__Suspend *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Suspend(struct soap*, const char*, int, const struct ns2__Suspend *, const char*);
SOAP_FMAC3 struct ns2__Suspend * SOAP_FMAC4 soap_get_ns2__Suspend(struct soap*, struct ns2__Suspend *, const char*, const char*);
SOAP_FMAC3 struct ns2__Suspend * SOAP_FMAC4 soap_in_ns2__Suspend(struct soap*, const char*, struct ns2__Suspend *, const char*);

#define soap_new_ns2__Suspend(soap, n) soap_instantiate_ns2__Suspend(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__Suspend(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__Suspend * SOAP_FMAC4 soap_instantiate_ns2__Suspend(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__Suspend(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__SuspendResponse
#define SOAP_TYPE_ns2__SuspendResponse (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__SuspendResponse(struct soap*, struct ns2__SuspendResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__SuspendResponse(struct soap*, const struct ns2__SuspendResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__SuspendResponse(struct soap*, const struct ns2__SuspendResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SuspendResponse(struct soap*, const char*, int, const struct ns2__SuspendResponse *, const char*);
SOAP_FMAC3 struct ns2__SuspendResponse * SOAP_FMAC4 soap_get_ns2__SuspendResponse(struct soap*, struct ns2__SuspendResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__SuspendResponse * SOAP_FMAC4 soap_in_ns2__SuspendResponse(struct soap*, const char*, struct ns2__SuspendResponse *, const char*);

#define soap_new_ns2__SuspendResponse(soap, n) soap_instantiate_ns2__SuspendResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__SuspendResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__SuspendResponse * SOAP_FMAC4 soap_instantiate_ns2__SuspendResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__SuspendResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__SetAdult
#define SOAP_TYPE_ns2__SetAdult (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__SetAdult(struct soap*, struct ns2__SetAdult *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__SetAdult(struct soap*, const struct ns2__SetAdult *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__SetAdult(struct soap*, const struct ns2__SetAdult *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SetAdult(struct soap*, const char*, int, const struct ns2__SetAdult *, const char*);
SOAP_FMAC3 struct ns2__SetAdult * SOAP_FMAC4 soap_get_ns2__SetAdult(struct soap*, struct ns2__SetAdult *, const char*, const char*);
SOAP_FMAC3 struct ns2__SetAdult * SOAP_FMAC4 soap_in_ns2__SetAdult(struct soap*, const char*, struct ns2__SetAdult *, const char*);

#define soap_new_ns2__SetAdult(soap, n) soap_instantiate_ns2__SetAdult(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__SetAdult(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__SetAdult * SOAP_FMAC4 soap_instantiate_ns2__SetAdult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__SetAdult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__SetAdultResponse
#define SOAP_TYPE_ns2__SetAdultResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__SetAdultResponse(struct soap*, struct ns2__SetAdultResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__SetAdultResponse(struct soap*, const struct ns2__SetAdultResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__SetAdultResponse(struct soap*, const struct ns2__SetAdultResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SetAdultResponse(struct soap*, const char*, int, const struct ns2__SetAdultResponse *, const char*);
SOAP_FMAC3 struct ns2__SetAdultResponse * SOAP_FMAC4 soap_get_ns2__SetAdultResponse(struct soap*, struct ns2__SetAdultResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__SetAdultResponse * SOAP_FMAC4 soap_in_ns2__SetAdultResponse(struct soap*, const char*, struct ns2__SetAdultResponse *, const char*);

#define soap_new_ns2__SetAdultResponse(soap, n) soap_instantiate_ns2__SetAdultResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__SetAdultResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__SetAdultResponse * SOAP_FMAC4 soap_instantiate_ns2__SetAdultResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__SetAdultResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__Resume
#define SOAP_TYPE_ns2__Resume (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__Resume(struct soap*, struct ns2__Resume *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__Resume(struct soap*, const struct ns2__Resume *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__Resume(struct soap*, const struct ns2__Resume *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Resume(struct soap*, const char*, int, const struct ns2__Resume *, const char*);
SOAP_FMAC3 struct ns2__Resume * SOAP_FMAC4 soap_get_ns2__Resume(struct soap*, struct ns2__Resume *, const char*, const char*);
SOAP_FMAC3 struct ns2__Resume * SOAP_FMAC4 soap_in_ns2__Resume(struct soap*, const char*, struct ns2__Resume *, const char*);

#define soap_new_ns2__Resume(soap, n) soap_instantiate_ns2__Resume(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__Resume(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__Resume * SOAP_FMAC4 soap_instantiate_ns2__Resume(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__Resume(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__ResumeResponse
#define SOAP_TYPE_ns2__ResumeResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ResumeResponse(struct soap*, struct ns2__ResumeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ResumeResponse(struct soap*, const struct ns2__ResumeResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ResumeResponse(struct soap*, const struct ns2__ResumeResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ResumeResponse(struct soap*, const char*, int, const struct ns2__ResumeResponse *, const char*);
SOAP_FMAC3 struct ns2__ResumeResponse * SOAP_FMAC4 soap_get_ns2__ResumeResponse(struct soap*, struct ns2__ResumeResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__ResumeResponse * SOAP_FMAC4 soap_in_ns2__ResumeResponse(struct soap*, const char*, struct ns2__ResumeResponse *, const char*);

#define soap_new_ns2__ResumeResponse(soap, n) soap_instantiate_ns2__ResumeResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__ResumeResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__ResumeResponse * SOAP_FMAC4 soap_instantiate_ns2__ResumeResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__ResumeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__Register
#define SOAP_TYPE_ns2__Register (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__Register(struct soap*, struct ns2__Register *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__Register(struct soap*, const struct ns2__Register *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__Register(struct soap*, const struct ns2__Register *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Register(struct soap*, const char*, int, const struct ns2__Register *, const char*);
SOAP_FMAC3 struct ns2__Register * SOAP_FMAC4 soap_get_ns2__Register(struct soap*, struct ns2__Register *, const char*, const char*);
SOAP_FMAC3 struct ns2__Register * SOAP_FMAC4 soap_in_ns2__Register(struct soap*, const char*, struct ns2__Register *, const char*);

#define soap_new_ns2__Register(soap, n) soap_instantiate_ns2__Register(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__Register(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__Register * SOAP_FMAC4 soap_instantiate_ns2__Register(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__Register(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__RegisterResponse
#define SOAP_TYPE_ns2__RegisterResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__RegisterResponse(struct soap*, struct ns2__RegisterResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__RegisterResponse(struct soap*, const struct ns2__RegisterResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__RegisterResponse(struct soap*, const struct ns2__RegisterResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__RegisterResponse(struct soap*, const char*, int, const struct ns2__RegisterResponse *, const char*);
SOAP_FMAC3 struct ns2__RegisterResponse * SOAP_FMAC4 soap_get_ns2__RegisterResponse(struct soap*, struct ns2__RegisterResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__RegisterResponse * SOAP_FMAC4 soap_in_ns2__RegisterResponse(struct soap*, const char*, struct ns2__RegisterResponse *, const char*);

#define soap_new_ns2__RegisterResponse(soap, n) soap_instantiate_ns2__RegisterResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__RegisterResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__RegisterResponse * SOAP_FMAC4 soap_instantiate_ns2__RegisterResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__RegisterResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__QueryPassword
#define SOAP_TYPE_ns2__QueryPassword (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__QueryPassword(struct soap*, struct ns2__QueryPassword *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__QueryPassword(struct soap*, const struct ns2__QueryPassword *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__QueryPassword(struct soap*, const struct ns2__QueryPassword *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__QueryPassword(struct soap*, const char*, int, const struct ns2__QueryPassword *, const char*);
SOAP_FMAC3 struct ns2__QueryPassword * SOAP_FMAC4 soap_get_ns2__QueryPassword(struct soap*, struct ns2__QueryPassword *, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryPassword * SOAP_FMAC4 soap_in_ns2__QueryPassword(struct soap*, const char*, struct ns2__QueryPassword *, const char*);

#define soap_new_ns2__QueryPassword(soap, n) soap_instantiate_ns2__QueryPassword(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__QueryPassword(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__QueryPassword * SOAP_FMAC4 soap_instantiate_ns2__QueryPassword(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__QueryPassword(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__QueryPasswordResponse
#define SOAP_TYPE_ns2__QueryPasswordResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__QueryPasswordResponse(struct soap*, struct ns2__QueryPasswordResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__QueryPasswordResponse(struct soap*, const struct ns2__QueryPasswordResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__QueryPasswordResponse(struct soap*, const struct ns2__QueryPasswordResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__QueryPasswordResponse(struct soap*, const char*, int, const struct ns2__QueryPasswordResponse *, const char*);
SOAP_FMAC3 struct ns2__QueryPasswordResponse * SOAP_FMAC4 soap_get_ns2__QueryPasswordResponse(struct soap*, struct ns2__QueryPasswordResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryPasswordResponse * SOAP_FMAC4 soap_in_ns2__QueryPasswordResponse(struct soap*, const char*, struct ns2__QueryPasswordResponse *, const char*);

#define soap_new_ns2__QueryPasswordResponse(soap, n) soap_instantiate_ns2__QueryPasswordResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__QueryPasswordResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__QueryPasswordResponse * SOAP_FMAC4 soap_instantiate_ns2__QueryPasswordResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__QueryPasswordResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__QueryAccountBlockHistory
#define SOAP_TYPE_ns2__QueryAccountBlockHistory (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__QueryAccountBlockHistory(struct soap*, struct ns2__QueryAccountBlockHistory *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__QueryAccountBlockHistory(struct soap*, const struct ns2__QueryAccountBlockHistory *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__QueryAccountBlockHistory(struct soap*, const struct ns2__QueryAccountBlockHistory *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__QueryAccountBlockHistory(struct soap*, const char*, int, const struct ns2__QueryAccountBlockHistory *, const char*);
SOAP_FMAC3 struct ns2__QueryAccountBlockHistory * SOAP_FMAC4 soap_get_ns2__QueryAccountBlockHistory(struct soap*, struct ns2__QueryAccountBlockHistory *, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryAccountBlockHistory * SOAP_FMAC4 soap_in_ns2__QueryAccountBlockHistory(struct soap*, const char*, struct ns2__QueryAccountBlockHistory *, const char*);

#define soap_new_ns2__QueryAccountBlockHistory(soap, n) soap_instantiate_ns2__QueryAccountBlockHistory(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__QueryAccountBlockHistory(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__QueryAccountBlockHistory * SOAP_FMAC4 soap_instantiate_ns2__QueryAccountBlockHistory(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__QueryAccountBlockHistory(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__QueryAccountBlockHistoryResponse
#define SOAP_TYPE_ns2__QueryAccountBlockHistoryResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__QueryAccountBlockHistoryResponse(struct soap*, struct ns2__QueryAccountBlockHistoryResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__QueryAccountBlockHistoryResponse(struct soap*, const struct ns2__QueryAccountBlockHistoryResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__QueryAccountBlockHistoryResponse(struct soap*, const struct ns2__QueryAccountBlockHistoryResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__QueryAccountBlockHistoryResponse(struct soap*, const char*, int, const struct ns2__QueryAccountBlockHistoryResponse *, const char*);
SOAP_FMAC3 struct ns2__QueryAccountBlockHistoryResponse * SOAP_FMAC4 soap_get_ns2__QueryAccountBlockHistoryResponse(struct soap*, struct ns2__QueryAccountBlockHistoryResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryAccountBlockHistoryResponse * SOAP_FMAC4 soap_in_ns2__QueryAccountBlockHistoryResponse(struct soap*, const char*, struct ns2__QueryAccountBlockHistoryResponse *, const char*);

#define soap_new_ns2__QueryAccountBlockHistoryResponse(soap, n) soap_instantiate_ns2__QueryAccountBlockHistoryResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__QueryAccountBlockHistoryResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__QueryAccountBlockHistoryResponse * SOAP_FMAC4 soap_instantiate_ns2__QueryAccountBlockHistoryResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__QueryAccountBlockHistoryResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__QueryAccountAdultStatus
#define SOAP_TYPE_ns2__QueryAccountAdultStatus (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__QueryAccountAdultStatus(struct soap*, struct ns2__QueryAccountAdultStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__QueryAccountAdultStatus(struct soap*, const struct ns2__QueryAccountAdultStatus *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__QueryAccountAdultStatus(struct soap*, const struct ns2__QueryAccountAdultStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__QueryAccountAdultStatus(struct soap*, const char*, int, const struct ns2__QueryAccountAdultStatus *, const char*);
SOAP_FMAC3 struct ns2__QueryAccountAdultStatus * SOAP_FMAC4 soap_get_ns2__QueryAccountAdultStatus(struct soap*, struct ns2__QueryAccountAdultStatus *, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryAccountAdultStatus * SOAP_FMAC4 soap_in_ns2__QueryAccountAdultStatus(struct soap*, const char*, struct ns2__QueryAccountAdultStatus *, const char*);

#define soap_new_ns2__QueryAccountAdultStatus(soap, n) soap_instantiate_ns2__QueryAccountAdultStatus(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__QueryAccountAdultStatus(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__QueryAccountAdultStatus * SOAP_FMAC4 soap_instantiate_ns2__QueryAccountAdultStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__QueryAccountAdultStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__QueryAccountAdultStatusResponse
#define SOAP_TYPE_ns2__QueryAccountAdultStatusResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__QueryAccountAdultStatusResponse(struct soap*, struct ns2__QueryAccountAdultStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__QueryAccountAdultStatusResponse(struct soap*, const struct ns2__QueryAccountAdultStatusResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__QueryAccountAdultStatusResponse(struct soap*, const struct ns2__QueryAccountAdultStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__QueryAccountAdultStatusResponse(struct soap*, const char*, int, const struct ns2__QueryAccountAdultStatusResponse *, const char*);
SOAP_FMAC3 struct ns2__QueryAccountAdultStatusResponse * SOAP_FMAC4 soap_get_ns2__QueryAccountAdultStatusResponse(struct soap*, struct ns2__QueryAccountAdultStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryAccountAdultStatusResponse * SOAP_FMAC4 soap_in_ns2__QueryAccountAdultStatusResponse(struct soap*, const char*, struct ns2__QueryAccountAdultStatusResponse *, const char*);

#define soap_new_ns2__QueryAccountAdultStatusResponse(soap, n) soap_instantiate_ns2__QueryAccountAdultStatusResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__QueryAccountAdultStatusResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct ns2__QueryAccountAdultStatusResponse * SOAP_FMAC4 soap_instantiate_ns2__QueryAccountAdultStatusResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__QueryAccountAdultStatusResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__RegisterResponse
#define SOAP_TYPE_PointerTo_ns1__RegisterResponse (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__RegisterResponse(struct soap*, _ns1__RegisterResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__RegisterResponse(struct soap*, _ns1__RegisterResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__RegisterResponse(struct soap*, const char *, int, _ns1__RegisterResponse *const*, const char *);
SOAP_FMAC3 _ns1__RegisterResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__RegisterResponse(struct soap*, _ns1__RegisterResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__RegisterResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__RegisterResponse(struct soap*, const char*, _ns1__RegisterResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__Register
#define SOAP_TYPE_PointerTo_ns1__Register (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Register(struct soap*, _ns1__Register *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Register(struct soap*, _ns1__Register *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Register(struct soap*, const char *, int, _ns1__Register *const*, const char *);
SOAP_FMAC3 _ns1__Register ** SOAP_FMAC4 soap_get_PointerTo_ns1__Register(struct soap*, _ns1__Register **, const char*, const char*);
SOAP_FMAC3 _ns1__Register ** SOAP_FMAC4 soap_in_PointerTo_ns1__Register(struct soap*, const char*, _ns1__Register **, const char*);

#ifndef SOAP_TYPE_PointerTons3__ProcessResult
#define SOAP_TYPE_PointerTons3__ProcessResult (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__ProcessResult(struct soap*, ns3__ProcessResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__ProcessResult(struct soap*, ns3__ProcessResult *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__ProcessResult(struct soap*, const char *, int, ns3__ProcessResult *const*, const char *);
SOAP_FMAC3 ns3__ProcessResult ** SOAP_FMAC4 soap_get_PointerTons3__ProcessResult(struct soap*, ns3__ProcessResult **, const char*, const char*);
SOAP_FMAC3 ns3__ProcessResult ** SOAP_FMAC4 soap_in_PointerTons3__ProcessResult(struct soap*, const char*, ns3__ProcessResult **, const char*);

#ifndef SOAP_TYPE_PointerTons3__QueryStringResult
#define SOAP_TYPE_PointerTons3__QueryStringResult (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__QueryStringResult(struct soap*, ns3__QueryStringResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__QueryStringResult(struct soap*, ns3__QueryStringResult *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__QueryStringResult(struct soap*, const char *, int, ns3__QueryStringResult *const*, const char *);
SOAP_FMAC3 ns3__QueryStringResult ** SOAP_FMAC4 soap_get_PointerTons3__QueryStringResult(struct soap*, ns3__QueryStringResult **, const char*, const char*);
SOAP_FMAC3 ns3__QueryStringResult ** SOAP_FMAC4 soap_in_PointerTons3__QueryStringResult(struct soap*, const char*, ns3__QueryStringResult **, const char*);

#ifndef SOAP_TYPE_PointerTons3__QueryAccountBlockHistoryResult
#define SOAP_TYPE_PointerTons3__QueryAccountBlockHistoryResult (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__QueryAccountBlockHistoryResult(struct soap*, ns3__QueryAccountBlockHistoryResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__QueryAccountBlockHistoryResult(struct soap*, ns3__QueryAccountBlockHistoryResult *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__QueryAccountBlockHistoryResult(struct soap*, const char *, int, ns3__QueryAccountBlockHistoryResult *const*, const char *);
SOAP_FMAC3 ns3__QueryAccountBlockHistoryResult ** SOAP_FMAC4 soap_get_PointerTons3__QueryAccountBlockHistoryResult(struct soap*, ns3__QueryAccountBlockHistoryResult **, const char*, const char*);
SOAP_FMAC3 ns3__QueryAccountBlockHistoryResult ** SOAP_FMAC4 soap_in_PointerTons3__QueryAccountBlockHistoryResult(struct soap*, const char*, ns3__QueryAccountBlockHistoryResult **, const char*);

#ifndef SOAP_TYPE_PointerTons3__AdultStatusResult
#define SOAP_TYPE_PointerTons3__AdultStatusResult (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__AdultStatusResult(struct soap*, ns3__AdultStatusResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__AdultStatusResult(struct soap*, ns3__AdultStatusResult *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__AdultStatusResult(struct soap*, const char *, int, ns3__AdultStatusResult *const*, const char *);
SOAP_FMAC3 ns3__AdultStatusResult ** SOAP_FMAC4 soap_get_PointerTons3__AdultStatusResult(struct soap*, ns3__AdultStatusResult **, const char*, const char*);
SOAP_FMAC3 ns3__AdultStatusResult ** SOAP_FMAC4 soap_in_PointerTons3__AdultStatusResult(struct soap*, const char*, ns3__AdultStatusResult **, const char*);

#ifndef SOAP_TYPE_PointerTons2__Exception
#define SOAP_TYPE_PointerTons2__Exception (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__Exception(struct soap*, ns2__Exception *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__Exception(struct soap*, ns2__Exception *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__Exception(struct soap*, const char *, int, ns2__Exception *const*, const char *);
SOAP_FMAC3 ns2__Exception ** SOAP_FMAC4 soap_get_PointerTons2__Exception(struct soap*, ns2__Exception **, const char*, const char*);
SOAP_FMAC3 ns2__Exception ** SOAP_FMAC4 soap_in_PointerTons2__Exception(struct soap*, const char*, ns2__Exception **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons3__BlockRecord
#define SOAP_TYPE_PointerToPointerTons3__BlockRecord (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons3__BlockRecord(struct soap*, ns3__BlockRecord **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons3__BlockRecord(struct soap*, ns3__BlockRecord **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons3__BlockRecord(struct soap*, const char *, int, ns3__BlockRecord **const*, const char *);
SOAP_FMAC3 ns3__BlockRecord *** SOAP_FMAC4 soap_get_PointerToPointerTons3__BlockRecord(struct soap*, ns3__BlockRecord ***, const char*, const char*);
SOAP_FMAC3 ns3__BlockRecord *** SOAP_FMAC4 soap_in_PointerToPointerTons3__BlockRecord(struct soap*, const char*, ns3__BlockRecord ***, const char*);

#ifndef SOAP_TYPE_PointerTons3__BlockRecord
#define SOAP_TYPE_PointerTons3__BlockRecord (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__BlockRecord(struct soap*, ns3__BlockRecord *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__BlockRecord(struct soap*, ns3__BlockRecord *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__BlockRecord(struct soap*, const char *, int, ns3__BlockRecord *const*, const char *);
SOAP_FMAC3 ns3__BlockRecord ** SOAP_FMAC4 soap_get_PointerTons3__BlockRecord(struct soap*, ns3__BlockRecord **, const char*, const char*);
SOAP_FMAC3 ns3__BlockRecord ** SOAP_FMAC4 soap_in_PointerTons3__BlockRecord(struct soap*, const char*, ns3__BlockRecord **, const char*);

#ifndef SOAP_TYPE_PointerTons1__GameAutoActivateResult
#define SOAP_TYPE_PointerTons1__GameAutoActivateResult (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__GameAutoActivateResult(struct soap*, ns1__GameAutoActivateResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__GameAutoActivateResult(struct soap*, ns1__GameAutoActivateResult *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__GameAutoActivateResult(struct soap*, const char *, int, ns1__GameAutoActivateResult *const*, const char *);
SOAP_FMAC3 ns1__GameAutoActivateResult ** SOAP_FMAC4 soap_get_PointerTons1__GameAutoActivateResult(struct soap*, ns1__GameAutoActivateResult **, const char*, const char*);
SOAP_FMAC3 ns1__GameAutoActivateResult ** SOAP_FMAC4 soap_in_PointerTons1__GameAutoActivateResult(struct soap*, const char*, ns1__GameAutoActivateResult **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
