
SO  = execute_global_script
COMPONENT = cellapp
SRCS =						\
	execute_global_script			\

ifndef MF_ROOT
export MF_ROOT := $(subst /bigworld/src/server/execute_global_script,,$(CURDIR))
endif

include $(MF_ROOT)/bigworld/src/server/common/common.mak

all::

