
SO  = message_monitor
COMPONENT = baseapp
SRCS =						\
	message_monitor			\

ifndef MF_ROOT
export MF_ROOT := $(subst /bigworld/src/server/execute_global_script,,$(CURDIR))
endif

include $(MF_ROOT)/bigworld/src/server/common/common.mak

all::

