
SO  = register_file_descriptor
COMPONENT = baseapp
SRCS =						\
	py_network			\

ifndef MF_ROOT
export MF_ROOT := $(subst /bigworld/src/server/register_file_descriptor,,$(CURDIR))
endif

include $(MF_ROOT)/bigworld/src/server/common/common.mak

all::

