
SO  = debug_extra
COMPONENT = cellapp
SRCS =						\
	debug_extra				\

ifndef MF_ROOT
export MF_ROOT := $(subst /bigworld/src/server_extensions/debug_extra,,$(CURDIR))
endif

include $(MF_ROOT)/bigworld/src/server/common/common.mak

all::

