
SO  = add_cellapp_id
COMPONENT = cellapp
SRCS =						\
	add_cellapp_id				\

ifndef MF_ROOT
export MF_ROOT := $(subst /bigworld/src/server/add_cellapp_id,,$(CURDIR))
endif

include $(MF_ROOT)/bigworld/src/server/common/common.mak

all::

